[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "roble"
description = "Processing IFU 3D spectral data"
readme = "README.rst"
license = "BSD-3-Clause"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["version"]
requires-python = ">=3.12.0"
dependencies = [
    "numpy",
    "scipy",
    "astropy",
    "jwst"
]
authors = [{name = "sugayu"}]
maintainers = [{name = "sugayu"}]

[project.urls]
Repository = "https://github.com/sugayu/roble.git"

[tool.setuptools.dynamic]
version = {attr = "roble.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
skip-string-normalization = true

[tool.mypy]

[[tool.mypy.overrides]]
module = [
       'scipy.*',
       'astropy.*',
       'gwcs.*',
       'jwst.*',
       'photutils.*',
       'importlib.*',
       'stdatamodels.*',
       'crds.*'
]
ignore_missing_imports = true
